### ISSUE TITLE
9.1 support?

### ISSUE THREAD

**Issue by Stoatwblr** [InfotelGLPI/manageentities#1]
Will this be ported to later versions or is that now built into glpi?

**Comment by Riesuu** [comment]
Bonjour,
un plugin énormément intéressant allez vous le porter sur la 9.1.2?

merci !

**Comment by xPocPoc974x** [comment]
Effectivement, ce plugin est super intéressant, et c'est exactement ce dont j'ai besoin.
Avez-vous l'intention de le mettre à jour pour le rendre compatible avec les dernières version de GLPI ?
Ce serait génial !
Merci !

**Comment by boscorelly** [comment]
Up, j'en aurais besoin aussi :(

**Comment by daldeas** [comment]
S'il pouvait être porté sur la 9.1 ou la 9.2 ce serait super !

**Comment by boscorelly** [comment]
J'ai commencé, mais j'ai pas trop de temps :/

**Comment by tsmr** [comment]
moi j'ai fini :D

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/manageentities/releases/tag/2.2.0

**Comment by boscorelly** [comment]
J'ai arrêté vu que tu m'as dit que tu le faisais :D
