### ISSUE TITLE
Problème : Génération du rapport d'intervention : &nbsp;

### ISSUE THREAD

**Issue by Dead-Red** [InfotelGLPI/manageentities#18]
Bonjour,

Je ne sais pas si il me manque quelque chose, mais lorsque je suis sur un ticket où je souhaites générer un rapport d'intervention,  dans les Champs :

-Libellé des activités 
- Détail des travaux réalisés

j'obtiens mon texte  mais il est illisible car j'ai pleins de : &nbsp; ou voici un extrait du détails des travaux réalisés : 

%3Cp%3EBonjour%20Nicolas%2C%3C%2Fp%3E%3Cp%3E%C2%A0%3C%2Fp%3E%3Cp%3EJe%20viens%20de%
20proc%C3%A9der%20%C3%A0%20la%20demande.%3C%2Fp%3E correspondant aux textes dans la tâche :

Bonjour Nicolas,

 

Je viens de procéder à la demande.

Comme si l' UTF8 n'était pas pris en compte ?

**Comment by tsmr** [comment]
Hello version of GLPI & plugin ?

**Comment by Dead-Red** [comment]
Hello,

GLPI : 9.5.2 and Plugin : 3.2.0

(Same problem with glpi in version 9.5.1)

**Comment by niquint** [comment]
Hello same problem for me GLPI 9.5.2 and plugin 3.2.0

**Comment by Dead-Red** [comment]
Hello,

When i active the debug mode, when i click on generate rapport...

I can seen in the ruban this red text :

SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EN OF MY TICKET TITLE '' at line 1 in query "SELECT `glpi_plugin_manageentities_critypes`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_plugin_manageentities_critypes` WHERE `glpi_plugin_manageentities_critypes`.`id` = 'THE TITLE OF MY TICKET '"

**Comment by gguib** [comment]
Hi,

Do you spoke of this part of text ?

![image](https://user-images.githubusercontent.com/56250594/100108658-4e999b00-2e6b-11eb-83aa-b56aa247b213.png)

I type random letters with spaces but it works fine.

**Comment by Dead-Red** [comment]
I have same problem with only some characters. 

If i print it : 
![20201124_211128](https://user-images.githubusercontent.com/31501256/100146363-165d8100-2e9a-11eb-8520-e0a1e967eba9.jpg)

**Comment by gguib** [comment]
Can you give me the exact sentence you typed pleased (with all characters) ?

**Comment by niquint** [comment]
![image](https://user-images.githubusercontent.com/74063150/100200844-7df9e780-2eff-11eb-9b00-437ebc623729.png)

Here the text is "L'impression des pdfs met 15 minutes depuis le poste d'Amandine"

**Comment by gguib** [comment]
![image](https://user-images.githubusercontent.com/56250594/100203671-32493d00-2f03-11eb-84a8-593f7b0f2869.png)

There is already a function wich decode utf8. Do you meet this problem elsewhere ?

**Comment by niquint** [comment]
the problem is only with the tasks. everything is ok elsewhere

**Comment by Dead-Red** [comment]
To me, i am unable to generate this report if i have no task in ticket.
(Same if i try to add an "intervenant")
![GLPI-Pb02](https://user-images.githubusercontent.com/31501256/100344582-567b4b80-2fe1-11eb-834e-1b54c307a802.png)

I dropdown the list, i select a user, and i click on the button : add ... (but nothing is happening)

**Comment by Dead-Red** [comment]
Hello,

Have you some news ?

**Comment by gguib** [comment]
Hi, 

Please update your version from master.

**Comment by Dead-Red** [comment]
ok, i must remove it from marketplace folder before ?

**Comment by gguib** [comment]
yes please. For the moment it is no more available from the market place, you must place it in the plugins folder.

**Comment by Dead-Red** [comment]
Ok, i have disable the plugin, and remove it after.  (It was not in marketplace folder but plugin :D)
I have move old folder on other directory
Download the master on server, rename folder ... Activate it. Ok nop
But now when i want generate repport i can't.
I chosse out of contract and i can clikc on modify but not more :(

I have only the  Dropdown menu to choose contract / Button : Modify and button : remove permanently

**Comment by gguib** [comment]
Lasts commits corrected url decode from tasks description.
You can't generate cri without task in ticket.
Please open other issue if you meet other problem from the origin's one.

**Comment by Dead-Red** [comment]
OK,  i have the problem with ticket with or without task ;(.

**Comment by Dead-Red** [comment]
i have upgrade the version, i have new problem : unable to generate CRI.

I have open new case as suggered. 
I close this
