### ISSUE TITLE
Unable to generate CRI after upgrade from master on github

### ISSUE THREAD

**Issue by Dead-Red** [InfotelGLPI/manageentities#19]
Hello,

With the GLPI 9.5.3 and the last plugin version 3.2.1 (download from github master as propose in last case) i have new problem.

Now in ticket, with or without task, i am unable to generate CRI.

But now when i want generate repport i can't.

I choose out of contract (same problem with contract) and i can click on modify but not more :(

I have only the Dropdown menu to choose contract - Button : Modify and button : remove permanently

And under buttons, i have the mention : " No item found"

**Comment by gguib** [comment]
Hi,

Please update with your version with master.

**Comment by Dead-Red** [comment]
Hello !

I already have the version of the master. I have followed this step on my last ticket as you have suggested.

The problem is with this last version. And i have try to downloaded today but the problem still same

**Comment by gguib** [comment]
Hello,

Have you tried with last release updated 2 days ago ?

https://github.com/InfotelGLPI/manageentities/releases/tag/3.2.1

**Comment by Dead-Red** [comment]
Yep ! Is better ! Now the button is present !!! Thank's you verry much for your working !

But new problem with title length (i create new case for the problem)

Thank's a lot !!
