### ISSUE TITLE
Catégorie de tickets

### ISSUE THREAD

**Issue by boscorelly** [InfotelGLPI/manageentities#2]
bonjour,

j'ai ce soucis quand je veux générer un rapport : Merci de configurer une catégorie de tâche de ticket avec le plugin. Pourtant j'ai bien assigné une catégorie à ma tache, et je ne trouve pas d'endroit où créer ce qu'il demande dans l'admin du plugin.

**Comment by amma35** [comment]
Dans la configuration de la catégorie, il y a un paramètre "Utiliser pour le calcul des CRI" si celui-ci n'est pas activé la tâche n'est pas valable dans le CRI.

**Comment by boscorelly** [comment]
Quand je suis dans la création d'une catégorie de taches, je n'ai pas cette option.

Ticket > Créer une tache > Catégories : ajouter une catégorie


Nom |   | Commentaires |  
-- | -- | -- | --
Comme enfant de |

**Comment by amma35** [comment]
Il y a un onglet "Portails entités" 
![2017-11-22 16_00_08-glpi - categories de tache](https://user-images.githubusercontent.com/15138371/33133831-4b8786fe-cf9e-11e7-8221-c88ec24a79db.png)

**Comment by boscorelly** [comment]
Vu merci !
