### ISSUE TITLE
Type d'intervention vide

### ISSUE THREAD

**Issue by lolokai** [InfotelGLPI/manageentities#22]
Bonjour,
Lorsque nous avons généré notre rapport d'intervention la colonne Type d'intervention reste vide malgré le fait que nous ayons sélectionné le type d'intervention lors de la génération du rapport.
![image](https://user-images.githubusercontent.com/2960490/117126096-99b0c600-ad9a-11eb-86f0-71441fb4c14b.png)
GLPI version : 9.5.5
Plugin version : 322

**Comment by tsmr** [comment]
Bonjour

Sur le contrat lié au ticket, au niveau de la prestation, avez-vous un tarif avec un type d'intervention associé ?

**Comment by cedrobert** [comment]
Bonjour,
Oui il y a bien un cout associé avec le type d'intervention:
![image](https://user-images.githubusercontent.com/43059901/117966767-5c69ac80-b335-11eb-817e-9574c8ccfe11.png)

**Comment by lolokai** [comment]
UP

**Comment by lolokai** [comment]
Le patch ne semble pas corriger le problème

**Comment by tsmr** [comment]
Vous êtes en mode Horaire ? Il faudrait déjà tester en mode Journalier (dans la configuration du plugin)

**Comment by lolokai** [comment]
Oui nous sommes en mode horaire

**Comment by cedrobert** [comment]
En mode Journalier cela est OK
