### ISSUE TITLE
Errors occured during migration

### ISSUE THREAD

**Issue by Badkempachi** [InfotelGLPI/manageentities#23]
Today, the GLPI was updated with a nightly build from 2022-01-29 00:21:21.
After performing the update, it was necessary to migrate the tables with the command “php bin/console glpi:migration:unsigned_keys” and 1 the table did not migrate and an error was received “Migration of column "glpi_plugin_manageentities_configs.documentcategories_id" cannot be done as it contains negative values.” What value should be set for glpi to perform the migration correctly?
![1](https://user-images.githubusercontent.com/97535165/151780888-493df679-c869-45c3-8c9b-3b2d2035bffc.png)
![2](https://user-images.githubusercontent.com/97535165/151780896-877746d8-376e-4019-9f1b-4a4de404713e.png)

**Comment by tsmr** [comment]
Hello. Change value to 0

**Comment by Badkempachi** [comment]
> Hello. Change value to 0

Thanks, this solved my problem and the migration is running.
