### ISSUE TITLE
Impossible d'ajouter le contrat et de générer en hors contrat

### ISSUE THREAD

**Issue by boscorelly** [InfotelGLPI/manageentities#3]
Bonjour,

je rencontre un soucis : quand je veux générer, je ne peux pas ajouter de contrat alors qu'il en existe bien un dans les contrats. J'ai oublié un truc ?

Et si je mets hors contrat, impossible de générer, le clic ne donne rien.

**Comment by keha35** [comment]
Bonjour,

Avez vous également ajouté une prestation au contrat que vous souhaitez lier au ticket?

**Comment by boscorelly** [comment]
Bonjour,

pourriez-vous me donner la bonne marche à suivre ?
Sans doute je m'y prends mal quelque part...

**Comment by keha35** [comment]
Bonjour,

Dans votre contrat, il faut aller dans "Détail du contrat" et ajouter une prestation de contrat avec une date de début, une date de fin, un type de contrat et un statut de contrat.

**Comment by ibisupport** [comment]
bonjour
j'ai un problème sensiblement proche.
j'ai pu créer une prestations de contrat, j'ai galé car le statut de contrat attend le code couleur en code html mais c'est précisé nulle part (en tout cas je n'ai pas trouvé)

par contre lorsque je suis dans le ticket > Rapport d'intervention 
La liste déroulante "Intervention sous contrat" est vide
La liste déroulante "Prestations du contrat" comporte bien la prestation créée

J'ai ajouté une tâche avec la catégorie qui dispose du "Utiliser pour le calcul des CRI" : OUI

par contre dans l'onglet Rapport d'intervention du ticket je n'arrive pas à lier mon ticket à mon contrat et de ce fait remonter le nombre d'heure consommé dans le contrat

**Comment by keha35** [comment]
Bonjour,

Est-ce toujours d'actualité ?

Avez vous bien défini un type de contrat sur vos contrat?
Avez vous défini un coût sur les prestation de contrat ?
