### ISSUE TITLE
Suivi mensuel et détails du contrat

### ISSUE THREAD

**Issue by boscorelly** [InfotelGLPI/manageentities#4]
Bonjour,

impossible d'accéder au suivi mensuel et aux détails du contrat.

J'ai par ailleurs cette erreur :

> 2017-12-07 14:16:05 [153@STSRV2K8_ING]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477 (0.000", 9.09Mio)
  _e() method is deprecated 
2017-12-07 14:16:05 [153@STSRV2K8_ING]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\autoload.function.php:168                      Toolbox::deprecated()
  plugins\manageentities\inc\entity.class.php:271    _e()
  plugins\manageentities\inc\entity.class.php:154    PluginManageentitiesEntity->showDescription()
  inc\commonglpi.class.php:482                       PluginManageentitiesEntity::displayTabContentForItem()
  ajax\common.tabs.php:96                            CommonGLPI::displayStandardTab()

> 2017-12-07 14:19:30 [147@STSRV2K8_ING]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\db.function.php:549                            Toolbox::deprecated()
  plugins\manageentities\inc\profile.class.php:140   TableExists()
  plugins\manageentities\inc\profile.class.php:187   PluginManageentitiesProfile::migrateOneProfile()
  :                                                  PluginManageentitiesProfile::initProfile()
  inc\plugin.class.php:1271                          call_user_func()
  inc\session.class.php:434                          Plugin::doHook()
  inc\session.class.php:152                          Session::changeProfile()
  inc\auth.class.php:813                             Session::init()
  front\login.php:79                                 Auth->Login()
2017-12-07 14:19:30 [147@STSRV2K8_ING]
  *** PHP Runtime Notice(2048): Declaration of PluginManageentitiesCompany::addFiles() should be compatible with CommonDBTM::addFiles(array $input, $options = Array)
  Backtrace :
  inc\autoload.function.php:347                      
  inc\autoload.function.php:347                      glpi_autoload()
  :                                                  glpi_autoload()
  plugins\manageentities\inc\entity.class.php:559    spl_autoload_call()
  inc\html.class.php:1359                            PluginManageentitiesEntity::getMenuContent()
  inc\html.class.php:5938                            Html::generateMenuSession()
  inc\html.class.php:1465                            Html::displayMainMenu()
  front\central.php:73                               Html::header()
2017-12-07 14:19:48 [153@STSRV2K8_ING]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477
  _e() method is deprecated 
2017-12-07 14:19:48 [153@STSRV2K8_ING]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\autoload.function.php:168                      Toolbox::deprecated()
  plugins\manageentities\inc\cridetail.class.php:293 _e()
  plugins\manageentities\inc\cridetail.class.php:447 PluginManageentitiesCriDetail::addReports()
  plugins\manageentities\inc\cridetail.class.php:93  PluginManageentitiesCriDetail::showReports()
  inc\commonglpi.class.php:482                       PluginManageentitiesCriDetail::displayTabContentForItem()
  ajax\common.tabs.php:96                            CommonGLPI::displayStandardTab()

**Comment by keha35** [comment]
Bonjour,

Le problème à été résolu en 9.3
