### ISSUE TITLE
PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function PluginManageentitiesCompany::addFiles()

### ISSUE THREAD

**Issue by samakehamed** [InfotelGLPI/manageentities#7]
Hi,
i got this error when trying to add new company: 
> **PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PluginManageentitiesCompany::addFiles(), 0 passed in /var/www/html/glpi/plugins/manageentities/inc/company.class.php on line 228 and at least 1 expected in /var/www/html/glpi/plugins/manageentities/inc/company.class.php:252\nStack trace:\n#0 /var/www/html/glpi/plugins/manageentities/inc/company.class.php(228): PluginManageentitiesCompany->addFiles()\n#1 /var/www/html/glpi/inc/commondbtm.class.php(1128): PluginManageentitiesCompany->post_addItem()\n#2 /var/www/html/glpi/plugins/manageentities/front/company.form.php(35): CommonDBTM->add(Array)\n#3 {main}\n thrown in /var/www/html/glpi/plugins/manageentities/inc/company.class.php on line 252, referer: http://my_server/glpi/plugins/manageentities/front/company.form.php**

GLPI version: 9.3.3
PHP 7.2.10
Plugin version: manageentities Version: 3.0.0

**Comment by keha35** [comment]
Hi,

A new release as been created.
It fix this problem.

**Comment by samakehamed** [comment]
Hi,
Ok. Thank you
