### ISSUE TITLE
Impossible d'ajouter un nouveau client

### ISSUE THREAD

**Issue by TedoA** [InfotelGLPI/manageentities#8]
Bonjour,

Votre Plugin à l'air très complet et pratique, mais je crains qu'il ne fonctionne pas correctement et que la documentation fournie ne soit pas à jour.

Je m'explique, quand je clique sur le "+" pour ajouter un nouveau client je ne peux le faire qu'une seule fois, quand je termine ma création de client et que je souhaite en faire un nouveau je suis bloqué sur le client que j'ai créé précédemment, est-ce moi qui utilise mal le plugin ou est-ce un réel problème ?

Ensuite, au sujet de la documentation il me semble qu'elle ne correspond pas à la dernière version de votre pulgin, car si on suit le processus d'utilisation du plugin on ne retrouve pas les mêmes intitulés, n'y les mêmes fonctionnalités.

Merci de votre réponse

**Comment by ales-infotel** [comment]
Bonjour,

Pour pouvoir ajouter un nouveau client, vous devez utiliser le bouton situé en dessous du formulaire nommé : "Réinitialiser tous les champs" en français ou "Reinitialize forms" en anglais.
