### ISSUE TITLE
Lier un ticket à un contrat ?

### ISSUE THREAD

**Issue by ibisupport** [InfotelGLPI/manageentities#9]
bonjour
j'ai un problème lorsque je souhaite affecter un ticket à un contrat

j'ai pu créer une prestations de contrat, j'ai galéré car le statut de contrat attend le code couleur en code html mais c'est précisé nulle part (en tout cas je n'ai pas trouvé)

par contre lorsque je suis dans le ticket > Rapport d'intervention
La liste déroulante "Intervention sous contrat" est vide
La liste déroulante "Prestations du contrat" comporte bien la prestation créée

J'ai ajouté une tâche avec la catégorie qui dispose du "Utiliser pour le calcul des CRI" : OUI

par contre dans l'onglet Rapport d'intervention du ticket je n'arrive pas à lier mon ticket à mon contrat et de ce fait remonter le nombre d'heure consommé dans le contrat

**Comment by marcamouzoun** [comment]
Bonjour,
Pour le code couleur tu peux utiliser #FFFFFF(couleur blanc) ou #FDEE00, ....
regarde les codes couleurs sur le net
Lors de la création du rapport qu'est ce que tu as comme erreur?

**Comment by iMano6938** [comment]
Bonjour,
J'ai le même problème. 
L'erreur est que tous les champs obligatoire ne sont pas définis. Sur la liste déroulante, je vois seulement les "prestations du contrat" mais il n'y a rien dans la liste déroulante "intervention sous contrat".

**Comment by marcamouzoun** [comment]
Bonjour,
Je n'ai pas compris, comment tu peux voir  les prestations du contrat et ne rien voir au  niveau de l'intervention sous contrat.
Mais c'est quand tu choisis le contrat (Intervention sous contrat) que tu peux choisir la Prestation du contrat non?
Tu peux réexpliquer ton problème ou envoie des captures, ce serait mieux.

**Comment by iMano6938** [comment]
Voici les captures 

![Annotation 2019-11-15 151804](https://user-images.githubusercontent.com/57762393/68949896-52f09a00-07bb-11ea-9e84-617351ba65c4.png)
![Annotation 2019-11-15 151820](https://user-images.githubusercontent.com/57762393/68949897-52f09a00-07bb-11ea-9764-bdd68e5e791f.png)
![Annotation 2019-11-15 151836](https://user-images.githubusercontent.com/57762393/68949898-53893080-07bb-11ea-8104-55690315ce4b.png)

**Comment by marcamouzoun** [comment]
Je viens de voir tes captures. C'est bizarre de ne pas avoir le  contrat mais d'avoir les prestations.
Je te propose de recréer un autre contrat
peux tu me montrer le contrat et les détails du contrat?
![image](https://user-images.githubusercontent.com/57600472/68966624-dbccfd00-07de-11ea-9bed-eae203157f25.png)

**Comment by keha35** [comment]
Bonjour,

Est-ce toujours d'actualité ?

Avez vous bien défini un type de contrat sur vos contrat? 
Avez vous défini un coût sur les prestation de contrat ?
